<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1685020773256' stop='1685020773274'>
    <name>test stocks API</name>
    <title>test stocks API</title>
    <test-cases>
        <test-case start='1685020773257' status='failed' stop='1685020773262'>
            <name>should validate response body</name>
            <title>should validate response body</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome'/>
                <parameter kind='environment-variable' name='BROWSER' value='chrome'/>
            </parameters>
            <steps/>
            <attachments/>
            <failure>
                <message>test validation failed</message>
                <stack-trace>AssertionError: test validation failed
                    at Context.&lt;anonymous> (C:\myworkfolder\Automation frameworks\apiAutomationInterview\test\specs\apiTests.js:52:20)
                    at Context.executeAsync (C:\myworkfolder\Automation frameworks\apiAutomationInterview\node_modules\@wdio\mocha-framework\node_modules\@wdio\utils\build\shim.js:333:27)
                    at Context.testFrameworkFnWrapper (C:\myworkfolder\Automation frameworks\apiAutomationInterview\node_modules\@wdio\mocha-framework\node_modules\@wdio\utils\build\test-framework\testFnWrapper.js:51:32)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>